import { afterEach, describe, expect, test } from "bun:test";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, existsSync, chmodSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { loadConfig, DEFAULT_TUNABLES, HARNESS_IDS, type Config } from "../src/config.js";
import { openDb, type DB } from "../src/db/index.js";
import { ingest } from "../src/ingest.js";
import type { Adapter, DiscoveredSource, IngestRecord } from "../src/adapters/types.js";
import { assembleChains } from "../src/chains.js";
import { blockWork, claimWork, ensureWork, finishWork, heartbeatWork, newestRelevantError } from "../src/jobs.js";
import { rebuildDatabase } from "../src/rebuild.js";
import { collectDoctorReport } from "../src/commands/doctor.js";

const dirs:string[]=[];
afterEach(()=>{for(const dir of dirs.splice(0))rmSync(dir,{recursive:true,force:true});});
function temp():string{const dir=mkdtempSync(join(tmpdir(),"atlas-phase3c-"));dirs.push(dir);return dir;}
function config(dbPath:string,root:string):Config{
 const sources={} as Config["sources"];
 for(const id of HARNESS_IDS)sources[id]={mode:"disabled",roots:[],disabledReason:"fixture owns only claude"};
 sources.claude={mode:"replace",roots:[root],disabledReason:null};
 return {sources,providers:[],launchers:[],tunables:{...DEFAULT_TUNABLES},dbPath};
}
function record(nativeId:string,assistant="synthetic assistant"):IngestRecord{return {
 nativeId,cwd:null,project:"fixture-project",title:null,startTs:1000,endTs:2000,models:[],transcriptBytes:100+assistant.length,origin:"human",parentNativeId:null,continuitySupport:"supported",continuityEvents:[],
 messages:[
  {ordinal:0,sourceOrdinal:4,role:"user",ts:1000,text:"synthetic user",toolText:null,hasTool:false,recordKind:"real_user",dialogueSide:"user",prose:"synthetic user",eventTs:1000,toolActivities:[],sourceRecordId:"fixture-user",sourceRecordUuid:null,sourceRecordTs:1000,sourceIdentityKind:"record-id"},
  {ordinal:1,sourceOrdinal:8,role:"assistant",ts:2000,text:assistant,toolText:null,hasTool:false,recordKind:"assistant_dialogue_prose",dialogueSide:"assistant",prose:assistant,eventTs:2000,toolActivities:[],sourceRecordId:"fixture-assistant",sourceRecordUuid:null,sourceRecordTs:2000,sourceIdentityKind:"record-id"},
 ],
 construction:{artifactKind:"dialogue_history",historyCompleteness:"complete",defaultSessionVisible:true,sourceValidationStatus:"current",sourceObservedTs:3000,project:{originalProjectKey:"fixture-project",canonicalProjectKey:"fixture-project",canonicalizationRuleVersion:"fixture-project-v1"},titleCandidates:[{value:"synthetic user",authority:"real_user_fallback",harnessSourceClass:"fixture-user",sourceRecordId:"fixture-user",sourceReference:null,sourceOrdinal:4,eligibilityRuleVersion:"fixture-title-v1"}],classificationRuleVersion:"fixture-class-v1",replayRuleVersion:"fixture-replay-v1"},
};}
function adapter(units:Map<string,IngestRecord>):Adapter{return {source:"claude",discover(roots){const out:DiscoveredSource[]=[];for(const root of roots)for(const [rel,rec] of units){const full=join(root,rel);if(existsSync(full))out.push({root,relPath:rel,fullPath:full,nativeId:`provisional-${rel}`,candidateKind:"fixture-candidate"});}return out;},parse(src){const rec=units.get(src.relPath);if(!rec)throw new Error("missing fixture record");const cloned=structuredClone(rec);if(cloned.construction)cloned.construction.sourceObservedTs=Math.floor(statSync(src.fullPath).mtimeMs);return {record:cloned,consumed:rec.transcriptBytes};}};}
async function fresh(root:string):Promise<{db:DB;dbPath:string}>{const dbPath=join(root,"atlas.db");return {db:await openDb(dbPath),dbPath};}

describe("Phase 3C catalog resolution",()=>{
 test("resolves exactly seven builtins and exact extend/replace/disabled forms",async()=>{const dir=temp(),cfgPath=join(dir,"config.toml"),db=join(dir,"atlas.db"),builtins={} as Record<(typeof HARNESS_IDS)[number],string[]>;for(const id of HARNESS_IDS)builtins[id]=[join(dir,`builtin-${id}`)];writeFileSync(cfgPath,`dbPath = ${JSON.stringify(db)}\n[sources.zcode]\nmode="replace"\nroots=[${JSON.stringify(join(dir,"zcode-survivor"))}]\n[sources.kilo]\nmode="extend"\nroots=[${JSON.stringify(join(dir,"kilo-retained.db"))}]\n[sources.kimi]\nmode="disabled"\nreason="fixture has no Kimi source"\n`);const cfg=await loadConfig(cfgPath,{bootstrap:false,builtinRoots:builtins});expect(Object.keys(cfg.sources)).toEqual([...HARNESS_IDS]);expect(cfg.sources.claude).toEqual({mode:"builtin",roots:builtins.claude,disabledReason:null});expect(cfg.sources.zcode.mode).toBe("replace");expect(cfg.sources.kilo.roots).toEqual([...builtins.kilo,join(dir,"kilo-retained.db")]);expect(cfg.sources.kimi.disabledReason).toBe("fixture has no Kimi source");});
 test("rejects empty/invalid plans before a configured DB exists",async()=>{for(const body of [`[sources.claude]\nmode="replace"\nroots=[]`,`[sources.claude]\nmode="disabled"`,`[sources.claude]\nmode="wat"`]){const dir=temp(),cfgPath=join(dir,"config.toml"),dbPath=join(dir,"must-not-open.db");writeFileSync(cfgPath,`dbPath=${JSON.stringify(dbPath)}\n${body}\n`);await expect(loadConfig(cfgPath,{bootstrap:false})).rejects.toThrow();expect(existsSync(dbPath)).toBe(false);}});
 test("direct CLI config rejection exits 2 before database creation",()=>{const dir=temp(),cfgPath=join(dir,"config.toml"),dbPath=join(dir,"must-not-open.db");writeFileSync(cfgPath,`dbPath=${JSON.stringify(dbPath)}\n[sources.claude]\nmode="replace"\nroots=[]\n`);const child=Bun.spawnSync({cmd:[process.execPath,join(import.meta.dir,"..","src","cli.ts"),"index","--config",cfgPath],cwd:join(import.meta.dir,".."),stdout:"pipe",stderr:"pipe"});expect(child.exitCode).toBe(2);expect(child.stderr.toString()).toContain("replace mode requires nonempty roots");expect(existsSync(dbPath)).toBe(false);});
});

describe("Phase 3C reconciliation and atomic construction",()=>{
 test("elects by semantic bytes, publishes all layers, and reconciles idempotently",async()=>{const dir=temp(),r1=join(dir,"root-a"),r2=join(dir,"root-b");mkdirSync(r1);mkdirSync(r2);writeFileSync(join(r1,"a.jsonl"),"fixture\n");writeFileSync(join(r2,"b.jsonl"),"fixture\n");const {db,dbPath}=await fresh(dir);try{const cfg=config(dbPath,r1);cfg.sources.claude={mode:"replace",roots:[r1,r2],disabledReason:null};const units=new Map([["a.jsonl",record("fixture-session","short")],["b.jsonl",record("fixture-session","a longer synthetic assistant")]]);const summaries=await ingest(db,cfg,{adapters:{claude:adapter(units)},configPath:join(dir,"config.toml")});const claude=summaries.find(s=>s.source==="claude")!;expect([claude.physicalDiscoveredUnits,claude.canonicalCandidates,claude.uniqueIdentities]).toEqual([2,2,1]);const s=db.prepare(`SELECT * FROM sessions WHERE harness='claude'`).get() as Record<string,unknown>;expect(s.source_path).toBe(join(r2,"b.jsonl"));expect(s.construction_status).toBe("valid");expect(s.default_session_visible).toBe(1);const metrics=db.prepare(`SELECT * FROM construction_metrics WHERE session_id=?`).get(s.id) as Record<string,unknown>;expect([metrics.raw_provenance_row_count,metrics.logical_record_count,metrics.dialogue_turn_count]).toEqual([2,2,2]);expect(Number((db.prepare(`SELECT COUNT(*) n FROM replay_election_evidence`).get() as {n:number}).n)).toBe(2);expect(Number((db.prepare(`SELECT COUNT(*) n FROM title_evidence WHERE selected=1`).get() as {n:number}).n)).toBe(1);expect(db.prepare(`SELECT candidate_kind,semantic_byte_tie FROM session_candidate_evidence ORDER BY root_ordinal`).all()).toEqual([{candidate_kind:"fixture-candidate",semantic_byte_tie:0},{candidate_kind:"fixture-candidate",semantic_byte_tie:0}]);const before=JSON.stringify(db.prepare(`SELECT harness,native_id,construction_generation,source_path,title FROM sessions`).all());await ingest(db,cfg,{adapters:{claude:adapter(units)},configPath:join(dir,"config.toml")});expect(JSON.stringify(db.prepare(`SELECT harness,native_id,construction_generation,source_path,title FROM sessions`).all())).toBe(before);expect(Number((db.prepare(`SELECT COUNT(*) n FROM sessions`).get() as {n:number}).n)).toBe(1);}finally{db.close();}});
 test("an unreachable winner root neither promotes a shorter duplicate nor orphans it",async()=>{const dir=temp(),r1=join(dir,"root-a"),r2=join(dir,"root-b");mkdirSync(r1);mkdirSync(r2);writeFileSync(join(r1,"winner.jsonl"),"fixture\n");writeFileSync(join(r2,"loser.jsonl"),"fixture\n");const {db,dbPath}=await fresh(dir);try{const cfg=config(dbPath,r1);cfg.sources.claude={mode:"replace",roots:[r1,r2],disabledReason:null};const units=new Map([["winner.jsonl",record("retained-session","the substantially longer elected synthetic transcript")],["loser.jsonl",record("retained-session","short")]]),fixtureAdapter=adapter(units);await ingest(db,cfg,{adapters:{claude:fixtureAdapter},configPath:join(dir,"config.toml")});rmSync(r1,{recursive:true,force:true});const partial=await ingest(db,cfg,{adapters:{claude:fixtureAdapter},configPath:join(dir,"config.toml")});expect(partial[0]).toMatchObject({uniqueIdentities:null,replaced:0,orphans:0});expect((db.prepare(`SELECT source_path,orphaned,source_validation_status FROM sessions WHERE native_id='retained-session'`).get() as Record<string,unknown>)).toEqual({source_path:join(r1,"winner.jsonl"),orphaned:0,source_validation_status:"snapshot_only"});expect(db.prepare(`SELECT elected,election_rule_version FROM session_candidate_evidence WHERE reconciliation_source_id=?`).all(partial[0]!.reconciliationSourceId)).toEqual([{elected:0,election_rule_version:"incomplete-no-election-v1"}]);}finally{db.close();}});
  test("collapses only agreeing stable-id plus original-time replay and materializes evidence",async()=>{const dir=temp(),root=join(dir,"root");mkdirSync(root);writeFileSync(join(root,"replay.jsonl"),"fixture\n");const {db,dbPath}=await fresh(dir);try{const replay=record("replay-session"),user=replay.messages[0]!,assistant=replay.messages[1]!;replay.messages=[{...user,ordinal:0,sourceOrdinal:4},{...user,ordinal:1,sourceOrdinal:5},{...assistant,ordinal:2,sourceOrdinal:8}];replay.transcriptBytes=333;const cfg=config(dbPath,root);await ingest(db,cfg,{adapters:{claude:adapter(new Map([["replay.jsonl",replay]]))},configPath:join(dir,"config.toml")});const metrics=db.prepare(`SELECT * FROM construction_metrics`).get() as Record<string,unknown>;expect([metrics.raw_provenance_row_count,metrics.logical_record_count,metrics.logical_replay_count]).toEqual([3,2,1]);expect(Number((db.prepare(`SELECT COUNT(*) n FROM replay_election_members`).get() as {n:number}).n)).toBe(3);expect((db.prepare(`SELECT member_count,replay_count FROM logical_messages ORDER BY logical_ordinal LIMIT 1`).get() as Record<string,unknown>)).toEqual({member_count:2,replay_count:1});}finally{db.close();}});
 test("same identity with a different timestamp remains singleton",async()=>{const dir=temp(),root=join(dir,"root");mkdirSync(root);writeFileSync(join(root,"sparse.jsonl"),"fixture\n");const {db,dbPath}=await fresh(dir);try{const sparse=record("sparse-session"),first=sparse.messages[0]!,assistant=sparse.messages[1]!;sparse.messages=[{...first,ordinal:0,sourceOrdinal:1},{...first,ordinal:1,sourceOrdinal:2,sourceRecordTs:1001},{...assistant,ordinal:2,sourceOrdinal:3}];sparse.transcriptBytes=334;await ingest(db,config(dbPath,root),{adapters:{claude:adapter(new Map([["sparse.jsonl",sparse]]))},configPath:join(dir,"config.toml")});const metrics=db.prepare(`SELECT logical_record_count,logical_replay_count FROM construction_metrics`).get();expect(metrics).toEqual({logical_record_count:3,logical_replay_count:0});}finally{db.close();}});
  test("a missing construction draft fails closed without raw or cursor fallback",async()=>{const dir=temp(),root=join(dir,"root");mkdirSync(root);writeFileSync(join(root,"legacy.jsonl"),"fixture\n");const {db,dbPath}=await fresh(dir);try{const invalid=record("invalid-session");delete invalid.construction;const result=await ingest(db,config(dbPath,root),{adapters:{claude:adapter(new Map([["legacy.jsonl",invalid]]))},configPath:join(dir,"config.toml")});expect(result[0]).toMatchObject({inserted:0,replaced:0,uniqueIdentities:null});expect(Number((db.prepare(`SELECT COUNT(*) n FROM sessions`).get() as {n:number}).n)).toBe(0);expect(Number((db.prepare(`SELECT COUNT(*) n FROM messages`).get() as {n:number}).n)).toBe(0);expect(Number((db.prepare(`SELECT COUNT(*) n FROM ingest_state`).get() as {n:number}).n)).toBe(0);}finally{db.close();}});
  test("fault after raw insertion rolls back generation and cursor",async()=>{const dir=temp(),root=join(dir,"root");mkdirSync(root);writeFileSync(join(root,"one.jsonl"),"fixture\n");const {db,dbPath}=await fresh(dir);try{const cfg=config(dbPath,root),units=new Map([["one.jsonl",record("fixture-session")]]);await ingest(db,cfg,{adapters:{claude:adapter(units)},configPath:join(dir,"config.toml")});const before=db.prepare(`SELECT construction_generation FROM sessions`).get() as {construction_generation:string};units.set("one.jsonl",record("fixture-session","changed synthetic assistant"));writeFileSync(join(root,"one.jsonl"),"fixture changed\n");await ingest(db,cfg,{adapters:{claude:adapter(units)},configPath:join(dir,"config.toml"),faultAfterRaw(){throw new Error("fixture transaction fault");}});const after=db.prepare(`SELECT construction_generation,construction_status FROM sessions`).get() as {construction_generation:string;construction_status:string};expect(after).toEqual({...before,construction_status:"valid"});expect((db.prepare(`SELECT prose FROM messages WHERE ordinal=1`).get() as {prose:string}).prose).toBe("synthetic assistant");expect(Number((db.prepare(`SELECT COUNT(*) n FROM ingest_state WHERE size=?`).get(statSize(join(root,"one.jsonl"))) as {n:number}).n)).toBe(0);}finally{db.close();}});
});

describe("Phase 3C chains and jobs",()=>{
 test("unchanged winner republishes the complete derived generation without raw rewrite",async()=>{const dir=temp(),root=join(dir,"root");mkdirSync(root);writeFileSync(join(root,"repair.jsonl"),"fixture\n");const {db,dbPath}=await fresh(dir);try{const repairRecord=record("repair-session");repairRecord.continuityEvents=[{kind:"compaction",sourceOrdinal:6,sourceRecordId:"fixture-compaction",sourceRecordTs:1500,sourceIdentityKind:"record-id",detail:"fixture boundary"}];const units=new Map([["repair.jsonl",repairRecord]]),cfg=config(dbPath,root),adapterFixture=adapter(units);await ingest(db,cfg,{adapters:{claude:adapterFixture},configPath:join(dir,"config.toml")});const rawIds=(db.prepare(`SELECT id FROM messages ORDER BY ordinal`).all() as Array<{id:number}>).map(row=>row.id);db.prepare(`DELETE FROM construction_metrics`).run();db.prepare(`DELETE FROM continuity_projection`).run();db.prepare(`DELETE FROM logical_message_members`).run();db.prepare(`DELETE FROM logical_messages`).run();const repaired=await ingest(db,cfg,{adapters:{claude:adapterFixture},configPath:join(dir,"config.toml")});expect(repaired[0]).toMatchObject({inserted:0,replaced:0,derivedRepaired:1,unchanged:0});expect((db.prepare(`SELECT id FROM messages ORDER BY ordinal`).all() as Array<{id:number}>).map(row=>row.id)).toEqual(rawIds);expect(Number((db.prepare(`SELECT COUNT(*) n FROM construction_metrics`).get() as {n:number}).n)).toBe(1);expect(Number((db.prepare(`SELECT COUNT(*) n FROM continuity_projection`).get() as {n:number}).n)).toBe(1);const again=await ingest(db,cfg,{adapters:{claude:adapterFixture},configPath:join(dir,"config.toml")});expect(again[0]).toMatchObject({derivedRepaired:0,unchanged:1});}finally{db.close();}});
  test("chain projection is deterministic and unresolved claims survive",async()=>{const dir=temp(),{db}=await fresh(dir);try{const ins=db.prepare(`INSERT INTO sessions(harness,native_id,source_path,ingested_at,parent_native_id,construction_generation,construction_status) VALUES ('claude',?,?,1,?,?,'valid')`);const p=Number((ins.run("parent","/fixture/parent",null,"fixture-parent") as {lastInsertRowid:number|bigint}).lastInsertRowid);const c=Number((ins.run("child","/fixture/child","parent","fixture-child") as {lastInsertRowid:number|bigint}).lastInsertRowid);const u=Number((ins.run("unresolved","/fixture/unresolved","missing","fixture-unresolved") as {lastInsertRowid:number|bigint}).lastInsertRowid);const first=assembleChains(db,"claude");const key=(db.prepare(`SELECT stable_key FROM chains`).get() as {stable_key:string}).stable_key;const second=assembleChains(db,"claude");expect(first).toEqual({chains:1,members:2});expect(second).toEqual(first);expect((db.prepare(`SELECT stable_key FROM chains`).get() as {stable_key:string}).stable_key).toBe(key);expect(Number((db.prepare(`SELECT COUNT(*) n FROM chains c WHERE c.member_count<>(SELECT COUNT(*) FROM sessions s WHERE s.chain_id=c.id)`).get() as {n:number}).n)).toBe(0);expect((db.prepare(`SELECT resolution_status,resolution_reason FROM lineage_claims WHERE session_id=?`).get(u) as {resolution_status:string;resolution_reason:string})).toEqual({resolution_status:"unresolved",resolution_reason:"missing_target"});expect((db.prepare(`SELECT chain_id FROM sessions WHERE id=?`).get(u) as {chain_id:number|null}).chain_id).toBeNull();void p;void c;}finally{db.close();}});
 test("canonical jobs block without provider and enforce one live lease",async()=>{const dir=temp(),{db}=await fresh(dir);try{const sid=Number((db.prepare(`INSERT INTO sessions(harness,native_id,source_path,ingested_at,construction_generation,construction_status) VALUES ('claude','job-session','/fixture/job',1,'fixture-generation','valid')`).run() as {lastInsertRowid:number|bigint}).lastInsertRowid);const blocked=blockWork(db,{kind:"tier1",sessionId:sid,inputVersion:"fixture-blocked",inputRevision:"fixture-generation"});expect((db.prepare(`SELECT current_status FROM job_work WHERE id=?`).get(blocked) as {current_status:string}).current_status).toBe("blocked");const pending=blockWork(db,{kind:"tier1",sessionId:sid,inputVersion:"fixture-pending",inputRevision:"fixture-generation"},"temporary block");db.prepare(`UPDATE job_work SET current_status='pending',blocked_reason=NULL WHERE id=?`).run(pending);const first=claimWork(db,{ownerToken:"fixture-owner",now:1000,leaseMs:100});expect(first?.id).toBe(pending);expect(claimWork(db,{ownerToken:"other-owner",now:1050,leaseMs:100})).toBeNull();expect(heartbeatWork(db,pending,"fixture-owner",1050,100)).toBe(true);expect(finishWork(db,pending,"other-owner","done")).toBe(false);expect(finishWork(db,pending,"fixture-owner","failed","newest fixture error",{now:1100})).toBe(true);expect(newestRelevantError(db,pending)).toBe("newest fixture error");expect(claimWork(db,{ownerToken:"backoff-owner",now:1200,leaseMs:100,workId:pending})).toBeNull();expect(claimWork(db,{ownerToken:"backoff-owner",now:61_100,leaseMs:100,workId:pending})?.attemptCount).toBe(3);db.prepare(`UPDATE sessions SET construction_generation='fixture-generation-new' WHERE id=?`).run(sid);expect(finishWork(db,pending,"backoff-owner","done",null,{now:61_150})).toBe(false);expect((db.prepare(`SELECT current_status FROM job_work WHERE id=?`).get(pending) as {current_status:string}).current_status).toBe("superseded");expect((db.prepare(`SELECT status FROM job_attempts WHERE work_id=? ORDER BY attempt_ordinal DESC LIMIT 1`).get(pending) as {status:string}).status).toBe("superseded");const redoInput={kind:"tier1",sessionId:sid,inputVersion:"fixture-redo",inputRevision:"fixture-generation-new"};const redo=ensureWork(db,redoInput);expect(claimWork(db,{ownerToken:"redo-owner",now:70_000,workId:redo})).not.toBeNull();expect(finishWork(db,redo,"redo-owner","done",null,{now:70_001})).toBe(true);ensureWork(db,redoInput,"pending",null,true);expect((db.prepare(`SELECT current_status FROM job_work WHERE id=?`).get(redo) as {current_status:string}).current_status).toBe("pending");expect(claimWork(db,{ownerToken:"redo-owner-2",now:70_002,workId:redo})?.attemptCount).toBe(2);}finally{db.close();}});
});
function statSize(path:string):number{return Bun.file(path).size;}


describe("Phase 3C rebuild preservation",()=>{
 test("rebuild blocks a missing stable target and preserves the original database",async()=>{const dir=temp(),root=join(dir,"root");mkdirSync(root);const {db,dbPath}=await fresh(dir);try{const sid=Number((db.prepare(`INSERT INTO sessions(harness,native_id,source_path,ingested_at) VALUES ('claude','missing-target','/fixture/missing',1)`).run() as {lastInsertRowid:number|bigint}).lastInsertRowid);db.prepare(`INSERT INTO summaries(session_id,tier,topic_line,msg_count_covered) VALUES (?,1,'must survive',0)`).run(sid);}finally{db.close();}await expect(rebuildDatabase(config(dbPath,root),{buildShadow:async()=>{}})).rejects.toThrow("summary target missing claude:missing-target");const original=await openDb(dbPath);try{expect((original.prepare(`SELECT topic_line FROM summaries`).get() as {topic_line:string}).topic_line).toBe("must survive");}finally{original.close();}});
  test("hard rebuild preserves summaries, anchors, tags, favorites, and canonical attempts",async()=>{const dir=temp(),root=join(dir,"root");mkdirSync(root);const {db,dbPath}=await fresh(dir);let sid=0;try{sid=Number((db.prepare(`INSERT INTO sessions(harness,native_id,source_path,ingested_at,construction_generation) VALUES ('claude','durable-session','/fixture/durable',1,'legacy-durable')`).run() as {lastInsertRowid:number|bigint}).lastInsertRowid);db.prepare(`INSERT INTO messages(session_id,ordinal,role,text,has_tool,tok_estimate) VALUES (?,0,'user','durable prose',0,1)`).run(sid);const summary=Number((db.prepare(`INSERT INTO summaries(session_id,tier,topic_line,msg_count_covered,coverage_basis,needs_revalidation) VALUES (?,1,'durable topic',1,'legacy_msg_count_v1',1)`).run(sid) as {lastInsertRowid:number|bigint}).lastInsertRowid);db.prepare(`INSERT INTO summary_anchors(summary_id,ord,topic,from_ordinal,to_ordinal,body) VALUES (?,0,'anchor',0,0,'body')`).run(summary);const tag=Number((db.prepare(`INSERT INTO tags(name,promoted_at) VALUES ('durable-tag',1)`).run() as {lastInsertRowid:number|bigint}).lastInsertRowid);db.prepare(`INSERT INTO session_tags(session_id,tag_id) VALUES (?,?)`).run(sid,tag);db.prepare(`INSERT INTO favorites(harness,native_id,span_text,span_hash,topic,scope,status,created_at,updated_at) VALUES ('claude','durable-session','durable favorite',?,'topic','session','ok',1,2)`).run(new Bun.CryptoHasher("sha256").update("durable favorite").digest("hex"));blockWork(db,{kind:"tier1",sessionId:sid,inputVersion:"durable-work",inputRevision:"legacy-durable"},"blocked exactly");}finally{db.close();}
 const cfg=config(dbPath,root),buildShadow=async(shadow:DB)=>{shadow.prepare(`INSERT INTO sessions(harness,native_id,source_path,ingested_at,construction_generation) VALUES ('claude','durable-session','/fixture/rebuilt',2,'rebuilt-generation')`).run();};const report=await rebuildDatabase(cfg,{hard:true,buildShadow});expect(report.summariesRestored).toBe(1);let durableFingerprint="";const rebuilt=await openDb(dbPath);try{expect((rebuilt.prepare(`SELECT topic_line,coverage_basis,needs_revalidation FROM summaries`).get() as Record<string,unknown>)).toEqual({topic_line:"durable topic",coverage_basis:"legacy_msg_count_v1",needs_revalidation:1});expect(Number((rebuilt.prepare(`SELECT COUNT(*) n FROM summary_anchors`).get() as {n:number}).n)).toBe(1);expect(Number((rebuilt.prepare(`SELECT COUNT(*) n FROM favorites`).get() as {n:number}).n)).toBe(1);expect(Number((rebuilt.prepare(`SELECT COUNT(*) n FROM job_work`).get() as {n:number}).n)).toBe(1);expect(Number((rebuilt.prepare(`SELECT COUNT(*) n FROM job_attempts`).get() as {n:number}).n)).toBe(1);durableFingerprint=JSON.stringify([rebuilt.prepare(`SELECT * FROM summaries`).all(),rebuilt.prepare(`SELECT * FROM summary_anchors`).all(),rebuilt.prepare(`SELECT * FROM tags`).all(),rebuilt.prepare(`SELECT * FROM session_tags`).all(),rebuilt.prepare(`SELECT * FROM favorites`).all(),rebuilt.prepare(`SELECT * FROM job_work`).all(),rebuilt.prepare(`SELECT * FROM job_attempts`).all()]);}finally{rebuilt.close();}await rebuildDatabase(cfg,{hard:true,buildShadow});const twice=await openDb(dbPath);try{expect(JSON.stringify([twice.prepare(`SELECT * FROM summaries`).all(),twice.prepare(`SELECT * FROM summary_anchors`).all(),twice.prepare(`SELECT * FROM tags`).all(),twice.prepare(`SELECT * FROM session_tags`).all(),twice.prepare(`SELECT * FROM favorites`).all(),twice.prepare(`SELECT * FROM job_work`).all(),twice.prepare(`SELECT * FROM job_attempts`).all()])).toBe(durableFingerprint);}finally{twice.close();}});
});


describe("Phase 3C doctor axes",()=>{
 test("reports healthy, root-newer degraded, and stale full walk down independently",async()=>{const dir=temp(),root=join(dir,"root"),cfgPath=join(dir,"config.toml"),schedulePath=join(dir,"schedule.plist");mkdirSync(root);writeFileSync(join(root,"one.jsonl"),"fixture\n");const {db,dbPath}=await fresh(dir);try{const cfg=config(dbPath,root),units=new Map([["one.jsonl",record("doctor-session")]]);await ingest(db,cfg,{adapters:{claude:adapter(units)},configPath:cfgPath,trigger:"scheduled"});writeFileSync(schedulePath,`${cfgPath}\n${dbPath}\n`);db.prepare(`UPDATE source_schedule_state SET schedule_kind='launchd',schedule_path=? WHERE source='claude'`).run(schedulePath);const finished=(db.prepare(`SELECT finished_at FROM reconciliation_groups ORDER BY id DESC LIMIT 1`).get() as {finished_at:number}).finished_at;const healthy=collectDoctorReport(db,cfg,finished+1000,cfgPath);expect(healthy.status).toBe("healthy");expect(healthy.lines.some(line=>line.includes("targeted ingestion")&&line.includes("never"))).toBe(true);writeFileSync(join(root,"new-unit.jsonl"),"fixture\n");const newer=collectDoctorReport(db,cfg,finished+2000,cfgPath);expect(newer.status).toBe("degraded");expect(newer.lines.some(line=>line.includes("root newer yes"))).toBe(true);rmSync(join(root,"new-unit.jsonl"));const stale=collectDoctorReport(db,cfg,finished+6*60*60_000+60_000,cfgPath);expect(stale.status).toBe("down");expect(stale.lines.some(line=>line.includes("full reconciliation")&&line.includes("DOWN"))).toBe(true);}finally{db.close();}});
});
